version: "3.8"

services:
  front-end:
    build:
      context: .
      Dockerfile: Dockerfile.client


    ports:
      - "3000:80"
    depends_on: backend 


  back-end:
    build:
      context: .
      Dockerfile: Dockerfile.server
    ports:
      - "3000:80"
    environment: 
      - DATABASE_URL=postgres://postgres:postdb@db:5432/Todos
    depends_on: -db

  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postdb
      - POSTGRES_DB=Todos
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


nginx:
  build:
    context: nginx
  container_name: nginx
  restart: always
  tty: true
  ports:
    - "8000:80"
  networks:
    - node-network
  depends_on:
    - back-end
    - front-end

networks:
  node-network:
    driver: bridge
