services:
  db:
    image: postgres:17
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postdb
      - POSTGRES_DB=Todos
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    expose:
      - "5432"

  back-end:
    build:
      context: ./src-server
      dockerfile: Dockerfile.server
    ports:
      - "3003:3001"
    environment:
      - DB_TABLE=Todos
      - DB_USER=postgres
      - DB_PASSWORD=postdb
      - DB_HOST=postgres
      - DB_PORT=5432
      - REACT_APP_API_URL=http://localhost:3003/api
    depends_on:
      - db

  front-end:
    build:
      context: ./src-client
      dockerfile: Dockerfile.client
    ports:
      - "3002:3000"
    command: npm run serve
    depends_on:
      - back-end

volumes:
  postgresql:

networks:
  default:
    name: postgresql_default
