services:
  front-end:
    build:
      context: ./src-client
      dockerfile: Dockerfile.client
    ports:
      - "3002:80"
    depends_on:
      - back-end

  back-end:
    build:
      context: ./
      dockerfile: ./src-server/Dockerfile.server
    ports:
      - "3003:80"
    environment:
      - DATABASE_URL=postgres://postgres:postdb@db:5432/Todos
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postdb
      - POSTGRES_DB=Todos
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    networks:
      - node-network
    depends_on:
      - back-end
      - front-end

networks:
  node-network:
    driver: bridge

volumes:
  db-data:
